---
- name: Create the configurations for sites
  template:
    src: "{{ item.value.template | default(apache_vhosts_template) }}"
    dest: "{{ apache_conf_path }}/sites-available/{{ item.key }}.conf"
  with_dict: "{{ apache_vhosts_sites }}"
  when: item.key not in apache_vhosts_remove_sites
  notify:
   - restart apache

- name: Create links for sites-enabled
  file:
    state: link
    src: "{{ apache_conf_path }}/sites-available/{{ item.key }}.conf"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ item.key }}.conf"
  with_dict: "{{ apache_vhosts_sites }}"
  when: item.key not in apache_vhosts_remove_sites
  notify:
   - restart apache

- name: Remove unwanted sites
  file:
    path: "{{ apache_conf_path }}/{{ item[0] }}/{{ item[1] }}.conf"
    state: absent
  with_nested:
    - [ 'sites-enabled', 'sites-available']
    - "{{ apache_vhosts_remove_sites }}"
  notify:
   - restart apache
